package ActiveCMDB::Model::CMDBv1;

use strict;
use base 'Catalyst::Model::DBIC::Schema';
use MooseX::Singleton;
use ActiveCMDB::ConfigFactory;
use ActiveCMDB::Common::Crypto;
use Data::Dumper;
use Logger;

my $config = ActiveCMDB::ConfigFactory->instance();
$config->load('cmdb');
my $dbinfo = $config->section('cmdb::database');
my $global = $config->section('cmdb::default');
if ( $dbinfo->{pwencr} == 1 ) {
	$dbinfo->{dbpass} = cmdb_decrypt($global->{keyname}, $dbinfo->{dbpass});
}


__PACKAGE__->config(
    schema_class => 'ActiveCMDB::Schema',
    
    connect_info => {
        dsn      => 'dbi:' . $dbinfo->{dbtype} . ':database=' . $dbinfo->{dbname} . ':host=%s',
        user     => $dbinfo->{dbuser},
        password => $dbinfo->{dbpass},
        dbhost   => $dbinfo->{dbhost}
    }
);

=head1 NAME

ActiveCMDB::Model::CMDBv1 - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ActiveCMDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ActiveCMDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Theo Bot

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
